apiVersion: v1
kind: Service
metadata:
  name: cca2324-bun-app-service
spec:
  selector:
    app: cca2324-bun-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 32101
  type: NodePort

