apiVersion: v1
kind: Service
metadata:
  name: cca2324-bun-app-service
spec:
  selector:
    app: cca2324-bun-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
